server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

jwt:
  secret: ${JWT_SECRET:AgriFarmsSuperSecretKeyForLocalJwtTokensValidation2026SecureString32BytesMin!}
  expiration: ${JWT_EXPIRATION_MS:2592000000} # 30 days in ms

spring:
  profiles:
    active: prod
  application:
    name: agri-farms-common-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://agri-prod-database.cr262csoswwh.ap-south-2.rds.amazonaws.com:5432/agri?currentSchema=%22agri-common%22}
    username: ${SPRING_DATASOURCE_USERNAME:agri_db_admin_user}
    password: ${SPRING_DATASOURCE_PASSWORD:zethon123$}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  sql:
    init:
      mode: always
  mail:
    host: smtp.zoho.in
    port: 587
    username: bharath@techxplorers.in
    password: ${SMTP_PASSWORD:SfmUcd5WK2p0}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            protocols: TLSv1.2

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:agri-app-storage-prod}
    region: ${AWS_REGION:ap-south-2}

msg91:
  authkey: ${MSG91_AUTHKEY:551740AvEkrLHO5I6a63711bP1}
  template-id: ${MSG91_TEMPLATE_ID:6a68ac1cf6d1ea492d0268b3}