server:
  port: 8083

spring:
  application:
    name: agri-farms-common-service

  datasource:
    url: jdbc:postgresql://192.168.29.238:5435/agrifarms
    username: agrifarms
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.zoho.in
    port: 587
    username: bharath@techxplorers.in
    password: ${SMTP_PASSWORD:SfmUcd5WK2p0}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            protocols: TLSv1.2
