-- liquibase formatted sql

-- =====================================================
-- changeset agrihub:1.0.0
-- Create USERS
-- =====================================================

CREATE TABLE IF NOT EXISTS users (
    user_id VARCHAR(50) PRIMARY KEY,
    phone_number VARCHAR(20) NOT NULL UNIQUE,
    full_name VARCHAR(150),
    role VARCHAR(50),
    district VARCHAR(100),
    village VARCHAR(100),
    profile_image_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- =====================================================
-- changeset agrihub:1.0.1
-- Create WORKER_GROUPS
-- =====================================================

CREATE TABLE IF NOT EXISTS worker_groups (
    group_id VARCHAR(50) PRIMARY KEY,
    owner_id VARCHAR(50) NOT NULL,
    group_name VARCHAR(150),
    male_count INT,
    female_count INT,
    price_per_male DECIMAL(10,2),
    price_per_female DECIMAL(10,2),
    skills TEXT,
    location VARCHAR(255),
    service_range_km INT,
    is_available BOOLEAN DEFAULT TRUE,
    rating DECIMAL(3,2) DEFAULT 0,
    approval_status VARCHAR(50),
    image_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_worker_groups_owner
        FOREIGN KEY (owner_id) REFERENCES users(user_id)
);

-- =====================================================
-- changeset agrihub:1.0.2
-- Create WORKER_GROUP_ROLES
-- =====================================================

CREATE TABLE IF NOT EXISTS worker_group_roles (
    role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id VARCHAR(50) NOT NULL,
    gender VARCHAR(10),
    count INT,
    task_name VARCHAR(150),
    CONSTRAINT fk_worker_group_roles_group
        FOREIGN KEY (group_id) REFERENCES worker_groups(group_id)
);

-- =====================================================
-- changeset agrihub:1.0.3
-- Create TRANSPORT_VEHICLES
-- =====================================================

CREATE TABLE IF NOT EXISTS transport_vehicles (
    vehicle_id VARCHAR(50) PRIMARY KEY,
    owner_id VARCHAR(50) NOT NULL,
    vehicle_type VARCHAR(100),
    vehicle_number VARCHAR(50),
    load_capacity VARCHAR(100),
    price_per_km_or_trip DECIMAL(10,2),
    driver_included BOOLEAN DEFAULT FALSE,
    service_area VARCHAR(255),
    location VARCHAR(255),
    is_available BOOLEAN DEFAULT TRUE,
    rating DECIMAL(3,2) DEFAULT 0,
    approval_status VARCHAR(50),
    image_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_transport_vehicle_owner
        FOREIGN KEY (owner_id) REFERENCES users(user_id)
);

-- =====================================================
-- changeset agrihub:1.0.4
-- Create EQUIPMENT
-- =====================================================

CREATE TABLE IF NOT EXISTS equipment (
    equipment_id VARCHAR(50) PRIMARY KEY,
    owner_id VARCHAR(50) NOT NULL,
    category VARCHAR(100),
    brand_model VARCHAR(150),
    condition_status VARCHAR(100),
    price_per_hour DECIMAL(10,2),
    operator_available BOOLEAN DEFAULT FALSE,
    location VARCHAR(255),
    is_available BOOLEAN DEFAULT TRUE,
    rating DECIMAL(3,2) DEFAULT 0,
    approval_status VARCHAR(50),
    image_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_equipment_owner
        FOREIGN KEY (owner_id) REFERENCES users(user_id)
);

-- =====================================================
-- changeset agrihub:1.0.5
-- Create SERVICES
-- =====================================================

CREATE TABLE IF NOT EXISTS services (
    service_id VARCHAR(50) PRIMARY KEY,
    owner_id VARCHAR(50) NOT NULL,
    service_type VARCHAR(100),
    business_name VARCHAR(150),
    description TEXT,
    equipment_used VARCHAR(255),
    price_rate DECIMAL(10,2),
    operator_included BOOLEAN DEFAULT FALSE,
    location VARCHAR(255),
    is_available BOOLEAN DEFAULT TRUE,
    rating DECIMAL(3,2) DEFAULT 0,
    approval_status VARCHAR(50),
    image_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_services_owner
        FOREIGN KEY (owner_id) REFERENCES users(user_id)
);

-- =====================================================
-- changeset agrihub:1.0.6
-- Create BOOKINGS
-- =====================================================

CREATE TABLE IF NOT EXISTS bookings (
    booking_id VARCHAR(50) PRIMARY KEY,
    farmer_id VARCHAR(50) NOT NULL,
    provider_id VARCHAR(50) NOT NULL,
    asset_id VARCHAR(50),
    asset_type VARCHAR(50),
    booking_date TIMESTAMP,
    scheduled_start_time TIMESTAMP,
    scheduled_end_time TIMESTAMP,
    status VARCHAR(50),
    total_amount DECIMAL(10,2),
    location_lat DECIMAL(10,7),
    location_lng DECIMAL(10,7),
    address_text TEXT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_booking_farmer
        FOREIGN KEY (farmer_id) REFERENCES users(user_id),
    CONSTRAINT fk_booking_provider
        FOREIGN KEY (provider_id) REFERENCES users(user_id)
);

-- =====================================================
-- changeset agrihub:1.0.7
-- Create REVIEWS
-- =====================================================

CREATE TABLE IF NOT EXISTS reviews (
    review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id VARCHAR(50) NOT NULL,
    reviewer_id VARCHAR(50) NOT NULL,
    reviewee_id VARCHAR(50) NOT NULL,
    rating INT,
    comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reviews_booking
        FOREIGN KEY (booking_id) REFERENCES bookings(booking_id),
    CONSTRAINT fk_reviews_reviewer
        FOREIGN KEY (reviewer_id) REFERENCES users(user_id),
    CONSTRAINT fk_reviews_reviewee
        FOREIGN KEY (reviewee_id) REFERENCES users(user_id)
);

-- =====================================================
-- changeset agrihub:1.0.8
-- Add updated_at auto column to worker_groups
-- =====================================================

ALTER TABLE worker_groups
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
